[package]
name = "hyperion"
version = "0.1.0"
authors = ["Julian Lazaras <umbrasdracodominus@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ion-shell = {git = "https://github.com/redox-os/ion"}
sqlite = "*"
http = "*"
rustls = "*"
tokio = {features = ["full"]}
log = "*"
